because user namespaces have been disabled
/home/gjones/scratch/lin16qubit/quantum/Quantum.py:302: OptimizeWarning: Unknown solver options: tol
  opt_result = minimize(self._cost_wrapper, x0=params, method=self.optimizer, callback=self._callback,
Loading dataset from /linear_train.bin... 
Successfully loaded /linear_train.bin into X and y data. 
Loading dataset from /linear_test.bin... 
Successfully loaded /linear_test.bin into X and y data. 
Training model with dataset /linear_train.bin 
 at time Fri Apr  5 21:37:10 2024... 
[Fri Apr  5 21:56:34 2024]  Iteration number: 0 with current cost as 0.3386525102786971 and parameters 
[-1.82734422  2.23743475 -2.12428041 -0.1165313   0.55388697 -2.7701087
  3.06858465  2.18960173  1.18551954 -1.06648353  0.60271433  1.14432434
  1.31029887 -1.87354741  0.7296502   2.88578364 -0.5453428  -0.47522496
 -2.02654285  0.72897325  1.60512619  2.83077008 -1.26456726 -0.25136105
 -2.39279378 -2.27309802  3.13337144  2.54856925 -0.67550815 -2.69002307
  1.51701612 -0.04647228 -2.34271359  2.04043159  1.15216279 -0.65055559
  1.04465341 -1.92056043 -0.32067999  2.32225928 -0.20585153  0.56637301
  2.6898312   1.07273389  2.5810285   2.94253977  2.76514618 -2.94578626
  0.36683982 -0.65725951  1.65159026  2.68042114 -0.25194965 -2.45807923
  2.63570541 -3.07930418  0.79129735 -0.7590176  -1.81776551  2.99868871
 -1.85887158 -1.63734088 -2.55370824  2.30926632 -2.25921323  1.98533552
  1.90881014  1.42517315  2.59930885  2.87147469  1.84732041  1.52137428
 -1.69866533 -2.34431217  1.23292411]. 
Traceback (most recent call last):
  File "/home/gjones/scratch/lin16qubit/main.py", line 329, in <module>
    main()
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/gjones/scratch/lin16qubit/main.py", line 189, in main
    model.fit(X_train, y_train, load_state=resume_file)
  File "/home/gjones/scratch/lin16qubit/quantum/Quantum.py", line 321, in fit
    self._save_partial_state(params, force=True)
  File "/home/gjones/scratch/lin16qubit/quantum/Quantum.py", line 237, in _save_partial_state
    os.remove('partial_state_model.bin')
FileNotFoundError: [Errno 2] No such file or directory: 'partial_state_model.bin'
/home/gjones/scratch/lin16qubit/quantum/Quantum.py:302: OptimizeWarning: Unknown solver options: tol
  opt_result = minimize(self._cost_wrapper, x0=params, method=self.optimizer, callback=self._callback,
Loading dataset from /linear_train.bin... 
Successfully loaded /linear_train.bin into X and y data. 
Loading dataset from /linear_test.bin... 
Successfully loaded /linear_test.bin into X and y data. 
Training model with dataset /linear_train.bin 
 at time Mon Apr  8 15:12:31 2024... 
[Mon Apr  8 15:28:54 2024]  Iteration number: 0 with current cost as 0.3386525102786971 and parameters 
[-1.82734422  2.23743475 -2.12428041 -0.1165313   0.55388697 -2.7701087
  3.06858465  2.18960173  1.18551954 -1.06648353  0.60271433  1.14432434
  1.31029887 -1.87354741  0.7296502   2.88578364 -0.5453428  -0.47522496
 -2.02654285  0.72897325  1.60512619  2.83077008 -1.26456726 -0.25136105
 -2.39279378 -2.27309802  3.13337144  2.54856925 -0.67550815 -2.69002307
  1.51701612 -0.04647228 -2.34271359  2.04043159  1.15216279 -0.65055559
  1.04465341 -1.92056043 -0.32067999  2.32225928 -0.20585153  0.56637301
  2.6898312   1.07273389  2.5810285   2.94253977  2.76514618 -2.94578626
  0.36683982 -0.65725951  1.65159026  2.68042114 -0.25194965 -2.45807923
  2.63570541 -3.07930418  0.79129735 -0.7590176  -1.81776551  2.99868871
 -1.85887158 -1.63734088 -2.55370824  2.30926632 -2.25921323  1.98533552
  1.90881014  1.42517315  2.59930885  2.87147469  1.84732041  1.52137428
 -1.69866533 -2.34431217  1.23292411]. 
Traceback (most recent call last):
  File "/home/gjones/scratch/lin16qubit/main.py", line 329, in <module>
    main()
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/gjones/scratch/lin16qubit/main.py", line 189, in main
    model.fit(X_train, y_train, load_state=resume_file)
  File "/home/gjones/scratch/lin16qubit/quantum/Quantum.py", line 321, in fit
    self._save_partial_state(params, force=True)
  File "/home/gjones/scratch/lin16qubit/quantum/Quantum.py", line 237, in _save_partial_state
    os.remove('partial_state_model.bin')
FileNotFoundError: [Errno 2] No such file or directory: 'partial_state_model.bin'
/home/gjones/scratch/lin16qubit/quantum/Quantum.py:302: OptimizeWarning: Unknown solver options: tol
  opt_result = minimize(self._cost_wrapper, x0=params, method=self.optimizer, callback=self._callback,
Loading dataset from /linear_train.bin... 
Successfully loaded /linear_train.bin into X and y data. 
Loading dataset from /linear_test.bin... 
Successfully loaded /linear_test.bin into X and y data. 
Training model with dataset /linear_train.bin 
 at time Mon Apr  8 16:23:04 2024... 
[Mon Apr  8 16:41:04 2024]  Iteration number: 0 with current cost as 0.3386525102786971 and parameters 
[-1.82734422  2.23743475 -2.12428041 -0.1165313   0.55388697 -2.7701087
  3.06858465  2.18960173  1.18551954 -1.06648353  0.60271433  1.14432434
  1.31029887 -1.87354741  0.7296502   2.88578364 -0.5453428  -0.47522496
 -2.02654285  0.72897325  1.60512619  2.83077008 -1.26456726 -0.25136105
 -2.39279378 -2.27309802  3.13337144  2.54856925 -0.67550815 -2.69002307
  1.51701612 -0.04647228 -2.34271359  2.04043159  1.15216279 -0.65055559
  1.04465341 -1.92056043 -0.32067999  2.32225928 -0.20585153  0.56637301
  2.6898312   1.07273389  2.5810285   2.94253977  2.76514618 -2.94578626
  0.36683982 -0.65725951  1.65159026  2.68042114 -0.25194965 -2.45807923
  2.63570541 -3.07930418  0.79129735 -0.7590176  -1.81776551  2.99868871
 -1.85887158 -1.63734088 -2.55370824  2.30926632 -2.25921323  1.98533552
  1.90881014  1.42517315  2.59930885  2.87147469  1.84732041  1.52137428
 -1.69866533 -2.34431217  1.23292411]. 
Traceback (most recent call last):
  File "/home/gjones/scratch/lin16qubit/main.py", line 330, in <module>
    main()
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/gjones/scratch/lin16qubit/main.py", line 189, in main
    model.fit(X_train, y_train, load_state=resume_file)
  File "/home/gjones/scratch/lin16qubit/quantum/Quantum.py", line 321, in fit
    self._save_partial_state(params, force=True)
  File "/home/gjones/scratch/lin16qubit/quantum/Quantum.py", line 237, in _save_partial_state
    os.remove('partial_state_model.bin')
FileNotFoundError: [Errno 2] No such file or directory: 'partial_state_model.bin'
/home/gjones/scratch/lin16qubit/quantum/Quantum.py:302: OptimizeWarning: Unknown solver options: tol
  opt_result = minimize(self._cost_wrapper, x0=params, method=self.optimizer, callback=self._callback,
Loading dataset from /linear_train.bin... 
Successfully loaded /linear_train.bin into X and y data. 
Loading dataset from /linear_test.bin... 
Successfully loaded /linear_test.bin into X and y data. 
Training model with dataset /linear_train.bin 
 at time Mon Apr  8 19:23:14 2024... 
[Mon Apr  8 19:40:02 2024]  Iteration number: 0 with current cost as 0.3386525102786971 and parameters 
[-1.82734422  2.23743475 -2.12428041 -0.1165313   0.55388697 -2.7701087
  3.06858465  2.18960173  1.18551954 -1.06648353  0.60271433  1.14432434
  1.31029887 -1.87354741  0.7296502   2.88578364 -0.5453428  -0.47522496
 -2.02654285  0.72897325  1.60512619  2.83077008 -1.26456726 -0.25136105
 -2.39279378 -2.27309802  3.13337144  2.54856925 -0.67550815 -2.69002307
  1.51701612 -0.04647228 -2.34271359  2.04043159  1.15216279 -0.65055559
  1.04465341 -1.92056043 -0.32067999  2.32225928 -0.20585153  0.56637301
  2.6898312   1.07273389  2.5810285   2.94253977  2.76514618 -2.94578626
  0.36683982 -0.65725951  1.65159026  2.68042114 -0.25194965 -2.45807923
  2.63570541 -3.07930418  0.79129735 -0.7590176  -1.81776551  2.99868871
 -1.85887158 -1.63734088 -2.55370824  2.30926632 -2.25921323  1.98533552
  1.90881014  1.42517315  2.59930885  2.87147469  1.84732041  1.52137428
 -1.69866533 -2.34431217  1.23292411]. 
Traceback (most recent call last):
  File "/home/gjones/scratch/lin16qubit/main.py", line 329, in <module>
    main()
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/gjones/scratch/lin16qubit/main.py", line 189, in main
    model.fit(X_train, y_train, load_state=resume_file)
  File "/home/gjones/scratch/lin16qubit/quantum/Quantum.py", line 321, in fit
    self._save_partial_state(params, force=True)
  File "/home/gjones/scratch/lin16qubit/quantum/Quantum.py", line 237, in _save_partial_state
    os.remove('partial_state_model.bin')
FileNotFoundError: [Errno 2] No such file or directory: 'partial_state_model.bin'
/home/gjones/scratch/lin16qubit/quantum/Quantum.py:302: OptimizeWarning: Unknown solver options: tol
  opt_result = minimize(self._cost_wrapper, x0=params, method=self.optimizer, callback=self._callback,
Loading dataset from /linear_train.bin... 
Successfully loaded /linear_train.bin into X and y data. 
Loading dataset from /linear_test.bin... 
Successfully loaded /linear_test.bin into X and y data. 
Training model with dataset /linear_train.bin 
 at time Wed Apr 10 06:44:17 2024... 
[Wed Apr 10 06:58:51 2024]  Iteration number: 0 with current cost as 0.3386525102786971 and parameters 
[-1.82734422  2.23743475 -2.12428041 -0.1165313   0.55388697 -2.7701087
  3.06858465  2.18960173  1.18551954 -1.06648353  0.60271433  1.14432434
  1.31029887 -1.87354741  0.7296502   2.88578364 -0.5453428  -0.47522496
 -2.02654285  0.72897325  1.60512619  2.83077008 -1.26456726 -0.25136105
 -2.39279378 -2.27309802  3.13337144  2.54856925 -0.67550815 -2.69002307
  1.51701612 -0.04647228 -2.34271359  2.04043159  1.15216279 -0.65055559
  1.04465341 -1.92056043 -0.32067999  2.32225928 -0.20585153  0.56637301
  2.6898312   1.07273389  2.5810285   2.94253977  2.76514618 -2.94578626
  0.36683982 -0.65725951  1.65159026  2.68042114 -0.25194965 -2.45807923
  2.63570541 -3.07930418  0.79129735 -0.7590176  -1.81776551  2.99868871
 -1.85887158 -1.63734088 -2.55370824  2.30926632 -2.25921323  1.98533552
  1.90881014  1.42517315  2.59930885  2.87147469  1.84732041  1.52137428
 -1.69866533 -2.34431217  1.23292411]. 
Traceback (most recent call last):
  File "/home/gjones/scratch/lin16qubit/main.py", line 329, in <module>
    main()
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/gjones/scratch/lin16qubit/main.py", line 189, in main
    model.fit(X_train, y_train, load_state=resume_file)
  File "/home/gjones/scratch/lin16qubit/quantum/Quantum.py", line 321, in fit
    self._save_partial_state(params, force=True)
  File "/home/gjones/scratch/lin16qubit/quantum/Quantum.py", line 237, in _save_partial_state
    os.remove('partial_state_model.bin')
FileNotFoundError: [Errno 2] No such file or directory: 'partial_state_model.bin'
/home/gjones/scratch/lin16qubit/quantum/Quantum.py:302: OptimizeWarning: Unknown solver options: tol
  opt_result = minimize(self._cost_wrapper, x0=params, method=self.optimizer, callback=self._callback,
/home/gjones/scratch/lin16qubit/quantum/Quantum.py:302: OptimizeWarning: Unknown solver options: tol
  opt_result = minimize(self._cost_wrapper, x0=params, method=self.optimizer, callback=self._callback,
Loading dataset from /linear_train.bin... 
Successfully loaded /linear_train.bin into X and y data. 
Loading dataset from /linear_test.bin... 
Successfully loaded /linear_test.bin into X and y data. 
Training model with dataset /linear_train.bin 
 at time Wed Apr 10 19:26:01 2024... 
[Wed Apr 10 19:43:11 2024]  Iteration number: 0 with current cost as 0.3386525102786971 and parameters 
[-1.82734422  2.23743475 -2.12428041 -0.1165313   0.55388697 -2.7701087
  3.06858465  2.18960173  1.18551954 -1.06648353  0.60271433  1.14432434
  1.31029887 -1.87354741  0.7296502   2.88578364 -0.5453428  -0.47522496
 -2.02654285  0.72897325  1.60512619  2.83077008 -1.26456726 -0.25136105
 -2.39279378 -2.27309802  3.13337144  2.54856925 -0.67550815 -2.69002307
  1.51701612 -0.04647228 -2.34271359  2.04043159  1.15216279 -0.65055559
  1.04465341 -1.92056043 -0.32067999  2.32225928 -0.20585153  0.56637301
  2.6898312   1.07273389  2.5810285   2.94253977  2.76514618 -2.94578626
  0.36683982 -0.65725951  1.65159026  2.68042114 -0.25194965 -2.45807923
  2.63570541 -3.07930418  0.79129735 -0.7590176  -1.81776551  2.99868871
 -1.85887158 -1.63734088 -2.55370824  2.30926632 -2.25921323  1.98533552
  1.90881014  1.42517315  2.59930885  2.87147469  1.84732041  1.52137428
 -1.69866533 -2.34431217  1.23292411]. 
Training complete taking 2103.0584325790405 total seconds. 
Now scoring model... 
Scoring complete taking 2.133145332336426 seconds. 
Saved predicted values as A2-A2-CNOT_Modified-Pauli-CRZ_predicted_values.csv
Model scores: {'MSE_train': (208.7879648110442,), 'R2_train': -0.011507616944938182, 'MAE_train': 12.72751351698471, 'MSE_test': 196.9276499790491, 'R2_test': -0.1870432278152494, 'MAE_test': 12.1438926610139}. 
Saved model results as A2-A2-CNOT_Modified-Pauli-CRZ_results.json. 
